

submit-local:
	spark-submit --master="spark://localhost:7077" --class consuming.Invoice --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.0 /opt/spark-apps/target/scala-2.13/apps_2.13-0.1.0-SNAPSHOT.jar
